import Head from "next/head";
import { useContext, useEffect } from "react";
import { PlayerContext } from "@/contexts/PlayerContext";
import { MusicDetail } from "@/interfaces/music";

interface Props {
  musicData: {
    code: number;
    data: MusicDetail[];
  };
}

export default function Home({ musicData }: Props) {
  const { setPlayerList } = useContext(PlayerContext);
  useEffect(() => {
    setPlayerList(musicData.data);
  }, [musicData.data, setPlayerList]);

  const handleButton = () => {
    setPlayerList(musicData.data.reverse());
    console.log("setPlayerList complete from index component");
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="">Home page</div>
        <button onClick={handleButton}>setData</button>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_SERVER_ADDRESS}/song/url/v1?id=405998841,33894312,298317,1888354230,210049&level=lossless`
  );
  const musicData = await res.json();
  return {
    props: { musicData },
  };
}
